name: Lock
description: Lock
inputs:
  mode:
    description: |
      lock, unlock, check
    required: true
  key:
    description: |
      lock key
    required: true
  key_prefix:
    description: |
      lock key prefix
    required: false
    default: "lock__"
  github_token:
    description: |
      GitHub Access Token
      contents:write - Create branches and commits
    required: false
    default: ${{ github.token }}
  repo_owner:
    description: |
      Repository owner.
    required: false
  repo_name:
    description: |
      Repository name.
    required: false
  message:
    description: |
      message.
    required: false
  post_unlock:
    description: |
      Whether unlock the key in the post step.
    default: "false"
    required: false
outputs:
  already_locked:
    description: Whether the key is already locked
  result:
    description: lock result
runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/index.js"
