name: Lock
description: Lock
inputs:
  branch:
    description: |
      lock branch
    required: true
  github_token:
    description: |
      GitHub Access Token
      contents:write - Create branches and commits
    required: false
    default: ${{ github.token }}
  repo_owner:
    description: |
      Repository owner.
    required: false
  repo_name:
    description: |
      Repository name.
    required: false
  message:
    description: |
      commit message.
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
