---
# Separate the workflow for actionlint to other workflows, because if a workflow for actionlint is broken actionlint isn't run
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - aqua/actionlint.yaml
jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aquaproj/aqua-installer@e6160e5a751bbcbd337a834eb75c15ba9ca206ae # v3.0.2
        with:
          aqua_version: v2.38.0
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: actionlint -ignore 'file "dist/index.js" does not exist'
