---
# Separate the workflow for actionlint to other workflows, because if a workflow for actionlint is broken actionlint isn't run
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - aqua/actionlint.yaml
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.36.2
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: actionlint -ignore 'file "dist/index.js" does not exist'
