---
name: Example deploy / check
on:
  workflow_dispatch:
    inputs:
      action:
        description: action
        required: true
        default: deploy
        type: choice
        options:
          - deploy
          - check
permissions:
  contents: write
jobs:
  deploy:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: inputs.action == 'deploy'
    steps:
      - uses: suzuki-shunsuke/lock-action@7ce9bcf15a765f862751c469e48877e590c1e532 # v0.1.0
        with:
          mode: lock
          key: example-deploy
      - run: echo "::notice::Deploying..." >&2
      - run: sleep 120

  check:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: inputs.action == 'check'
    steps:
      - uses: suzuki-shunsuke/lock-action@7ce9bcf15a765f862751c469e48877e590c1e532 # v0.1.0
        id: check
        with:
          mode: check
          key: example-deploy
      - run: |
          echo "::error:: The key $KEY is being locked"
          exit 1
        if: steps.check.outputs.already_locked == 'true'
