name: pull request

on:
  push:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BRANCH: latest
    steps:
      - uses: suzuki-shunsuke/build-js-action@feat-first-pr
        with:
          version: latest
