---
name: wc-create-pr-branch
run-name: wc-create-pr-branch (${{inputs.pr}})
on:
  workflow_call:
    inputs:
      pr:
        description: "Pull Request Number"
        required: true
        type: number
      is_comment:
        description: If the comment is posted
        required: false
        default: false
        type: boolean
    secrets:
      gh_app_id:
        required: true
      gh_app_private_key:
        required: true

permissions:
  contents: write
  pull-requests: write

env:
  PR_NUMBER: ${{inputs.pr}}
  PR_BRANCH: pr/${{inputs.pr}}

jobs:
  create-pr-branch:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: suzuki-shunsuke/build-js-action@feat-first-pr
        with:
          version: ${{env.PR_BRANCH}}
          is_comment: ${{inputs.is_comment}}
