---
name: Test
on:
  workflow_call:
    secrets:
      TAKUMI_GUARD_BOT_ID:
        required: true

jobs:
  test-1:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # Required for OIDC
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
          cache: npm
      - uses: flatt-security/setup-takumi-guard-npm@9a5d797c2085b6326d3a2985c08e3a114b9b88c1 # v1.1.1
        with:
          bot-id: ${{secrets.TAKUMI_GUARD_BOT_ID}}
      - run: npm ci
      - run: npm run build

      - name: Unlock test-1
        uses: ./
        with:
          mode: unlock
          key: test-1
      - name: Lock test-1
        uses: ./
        with:
          mode: lock
          key: test-1
          post_unlock: "true"
          max_wait_seconds: "30"
          wait_interval_seconds: "5"
      - name: Check test-1
        uses: ./
        id: check
        with:
          mode: check
          key: test-1
      - name: Check the output of check step
        run: echo "$OUTPUTS"
        env:
          OUTPUTS: ${{toJSON(steps.check.outputs)}}

  test-2:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # Required for OIDC
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
          cache: npm
      - uses: flatt-security/setup-takumi-guard-npm@9a5d797c2085b6326d3a2985c08e3a114b9b88c1 # v1.1.1
        with:
          bot-id: ${{secrets.TAKUMI_GUARD_BOT_ID}}
      - run: npm ci
      - run: npm run build

      - name: Check test-2
        uses: ./
        id: check
        with:
          mode: check
          key: test-2
      - name: Check the output of check step
        run: echo "$OUTPUTS"
        env:
          OUTPUTS: ${{toJSON(steps.check.outputs)}}
      - name: Lock test-2
        uses: ./
        with:
          mode: lock
          key: test-2
          max_wait_seconds: "30"
          wait_interval_seconds: "5"
      - name: Remove test-2
        uses: ./
        with:
          mode: unlock
          key: test-2
          remove_key_when_unlock: "true"
      - name: Remove test-2 again
        uses: ./
        with:
          mode: unlock
          key: test-2
          remove_key_when_unlock: "true"
